Configure DB Migrator IAM role and permissions
tecton-ai/tecton-terraform-setup pull request #121
Opened 2024-01-05 22:14 UTC by colehendo

This adds an IAM role and ensuing permissions necessary for running the database migrator. The role is used by the Kubernetes Service Account, while the `db-migrator` pod uses the `tecton-<cluster name>-eks-worker-role` IAM role under the hood. Therefore, the `tecton-<cluster name>-database-migrator` IAM role only needs the assume role policy, but no actual permissions, while the `tecton-<cluster name>-eks-worker-role` IAM role requires the RDS snapshot permissions needed to perform the database migration. The RDS snapshot permissions were based off of the permissions [currently used for SaaS clusters](https://github.com/tecton-ai/tecton/blob/master/infrastructure/deployment/modules/roles/main.tf#L270)

This was successfully tested on an internal cluster. The test ticket can be [tracked here](https://tecton.atlassian.net/browse/TEC-18067), and the rollout ticket can be [tracked here](https://tecton.atlassian.net/browse/TEC-18068).

This PR will not be merged until we begin the rollout plan, which includes documentation updates.

2024-01-05 22:27 UTC, scottames requested changes

2024-01-05 22:27 UTC, scottames commented on roles/roles.tf
> +# DEVOPS [Common : Databricks and EMR]
```suggestion
# Database Migrator [Common : Databricks and EMR]
```

2024-01-05 22:27 UTC, scottames commented on roles/roles.tf
> +    DEPLOYMENT_NAME = var.deployment_name
I don't think you need this (the template doesn't use it?)

2024-01-05 22:27 UTC, scottames commented on roles/roles.tf
> +# DEVOPS [Common : Databricks and EMR]
```suggestion
# Database Migrator [Common : Databricks and EMR]
```

2024-01-05 22:27 UTC, scottames commented on roles/roles.tf
> +# DEVOPS [Common : Databricks and EMR]
```suggestion
# Database Migrator [Common : Databricks and EMR]
```

2024-01-05 22:34 UTC, colehendo commented on roles/roles.tf
> +    DEPLOYMENT_NAME = var.deployment_name
Good catch, the template used it initially, but I had to broaden the scope as that caused errors. I'll remove it

2024-01-08 15:40 UTC, scottames approved these changes

2024-01-17 21:19 UTC, merged